
# This file was auto-generated by Parser Tongue.

import re
import logging
from datetime import datetime, timezone

# Get a logger instance (optional, but good practice)
logger = logging.getLogger(__name__)

# We pre-compile the regex for better performance
# (I've slightly simplified the regex to just use re.match and groups)
COMBINED_REGEX = re.compile(
    r'(\d+\.\d+\.\d+\.\d+) - - \[(.*?)\] "(\w+) (.*?) HTTP\/(\d+\.\d+)" (\d+) (\d+|-) (".*?"|"-") (".*?"|"-")'
)
# Headers for the COMBINED format
COMBINED_HEADERS = [
    'ip_address', 'timestamp', 'method', 'requested_url', 'http_version',
    'status_code', 'bytes_tx', 'referer', 'user_agent'
]

COMMON_REGEX = re.compile(
    r'(\d+\.\d+\.\d+\.\d+) - - \[(.*?)\] "(\w+) (.*?) HTTP\/(\d+\.\d+)" (\d+) (\d+|-)'
)
# Headers for the COMMON format (fewer fields)
COMMON_HEADERS = [
    'ip_address', 'timestamp', 'method', 'requested_url', 'http_version',
    'status_code', 'bytes_tx'
]

class ApacheAccessLog:
    """
    This is the template class for a Parser Tongue parser.
    """

    # --- PARSER METADATA ---
    parser_name = "Apache Access Log"
    parser_description = "Parses Apache Common and Combined access log formats."
    supported_extensions = ['.log', '.txt']

    def can_parse(self, filepath, file_content_sample):
        """
        Returns a confidence score (0-100) of how likely this
        parser is to handle the given file.
        """
        # Decode for regex text matching, ignoring errors
        sample_text = file_content_sample.decode('utf-8', 'ignore')
        
        # Look for the classic Apache log pattern
        if re.search(r'\[.*?\] "\w+ .*? HTTP', sample_text):
            return 90  # High confidence
        return 0

    def parse(self, filepath, is_batch=False):
        """
        Parses the file and returns a list of dictionaries.
        """
        parsed_data = []
        
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue # Skip empty lines

                    # 1. Try to match the (more specific) Combined Log Format first
                    match = COMBINED_REGEX.match(line)
                    if match:
                        # Zip headers and groups into a dictionary
                        record = dict(zip(COMBINED_HEADERS, match.groups()))
                        
                        # Add our required normalized timestamp
                        record['Timestamp_UTC'] = self._normalize_time(record['timestamp'])
                        parsed_data.append(record)
                        continue # Move to the next line

                    # 2. If not, try the Common Log Format
                    match = COMMON_REGEX.match(line)
                    if match:
                        # Zip headers and groups into a dictionary
                        record = dict(zip(COMMON_HEADERS, match.groups()))
                        
                        # Add our required normalized timestamp
                        record['Timestamp_UTC'] = self._normalize_time(record['timestamp'])
                        parsed_data.append(record)
                        continue # Move to the next line
                    
                    # 3. Handle your 'else' case (unparsed lines)
                    # Instead of splitting, we'll just log it as a warning
                    logger.warning(f"Failed to parse line in {filepath.name}: {line}")

        except Exception as e:
            logger.error(f"Error parsing file {filepath.name}: {e}", exc_info=True)
            
        return parsed_data

    # Helper method for time conversion
    def _normalize_time(self, timestamp_str):
        """
        Converts Apache timestamp string to a UTC ISO-8601 string.
        Example input: '10/Oct/2000:13:55:36 -0700'
        """
        try:
            # 1. This is the Apache-specific parsing logic (KEEP THIS)
            dt = datetime.strptime(timestamp_str, '%d/%b/%Y:%H:%M:%S %z')
            
            # 2. This is the NEW standardization logic (ADD THIS)
            dt_utc = dt.astimezone(timezone.utc)
            dt_no_micros = dt_utc.replace(microsecond=0)
            return dt_no_micros.isoformat().replace('+00:00', 'Z')
            
        except (ValueError, TypeError):
            logger.warning(f"Could not parse timestamp: {timestamp_str}")
            return timestamp_str