
# This file was auto-generated by Parser Tongue.

import logging
from datetime import datetime, timezone  # Common import for timestamps

# Get a logger instance
logger = logging.getLogger(__name__)

# --- COMMON PARSER DEFINITIONS ---
# It's good practice to pre-compile regex patterns for efficiency
# EXAMPLE_REGEX = re.compile(
#     r'(\d+\.\d+\.\d+\.\d+) - (.*?) \[(.*?)\]'
# )
#
# EXAMPLE_HEADERS = ['ip', 'user', 'timestamp']
# ---

class IISLog:
    """
    This is the template class for a Parser Tongue parser.
    """

    # --- PARSER METADATA ---
    parser_name = "IIS Log"
    parser_description = "Parses W3C Extended Log Format used by Microsoft IIS."
    supported_extensions = ['.log', '.txt']

    def can_parse(self, filepath, file_content_sample):
        """
        Returns a confidence score (0-100)
        """
        # IIS logs reliably start with this comment.
        if b'#Software: Microsoft Internet Information Services' in file_content_sample:
            return 100 # Very high confidence
        return 0

    def parse(self, filepath, is_batch=False):
        """
        Parses the file and returns a list of dictionaries.
        This parser is 'stateful' - it must find headers before processing data.
        """
        parsed_data = []
        headers = []
        
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue

                    # 1. Look for the header directive
                    if line.startswith('#Fields:'):
                        # Split the line, skip the '#Fields: ' prefix, and store headers
                        headers = line[9:].split(' ')
                        logger.debug(f"Found IIS headers in {filepath.name}: {headers}")
                        continue

                    # 2. Skip any other comments
                    if line.startswith('#'):
                        continue

                    # 3. If we have headers, this must be a data line
                    if headers:
                        values = line.split(' ')
                        
                        # Combine headers and values into a dictionary
                        record = dict(zip(headers, values))
                        
                        # Normalize the timestamp
                        record['Timestamp_UTC'] = self._normalize_time(record)
                        parsed_data.append(record)

        except Exception as e:
            logger.error(f"Error parsing file {filepath.name}: {e}", exc_info=True)
            
        return parsed_data

    # --- HELPER METHODS ---
    def _normalize_time(self, record):
        """
        Combines 'date' and 'time' fields and converts to UTC ISO string.
        Assumes the original log time is UTC, as IIS logs lack timezone info.
        """
        try:
            # Combine the two fields into one string
            timestamp_str = f"{record.get('date')} {record.get('time')}"
            
            # Parse the combined string
            dt = datetime.strptime(timestamp_str, '%Y-%m-%d %H:%M:%S')
            
            # IIS logs don't have timezone info. A safe default is to assume
            # the server was configured to log in UTC.
            dt_utc = dt.replace(tzinfo=timezone.utc)
            
            return dt_utc.isoformat()
            
        except (ValueError, KeyError):
            # If parsing fails or keys are missing, return a placeholder
            logger.warning(f"Could not parse timestamp from record: {record}")
            return "Timestamp-Parse-Error"