# core/templates.py

import logging

logger = logging.getLogger(__name__)

# --- V1: FILE PARSER TEMPLATE ---

PARSER_TEMPLATE_STRING = """
# This file was auto-generated by Parser Tongue.

import logging
import re
from datetime import datetime, timezone
from pathlib import Path

# Get a logger instance
logger = logging.getLogger(__name__)

# --- COMMON PARSER DEFINITIONS ---
# EXAMPLE_REGEX = re.compile(
#     r'(\d+\.\d+\.\d+\.\d+) - (.*?) \[(.*?)\]'
# )
#
# EXAMPLE_HEADERS = ['ip', 'user', 'original_timestamp']
# ---

class ParserTemplate:
    \"\"\"
    This is the template class for a Parser Tongue file parser.
    \"\"\"

    # --- PARSER METADATA (REQUIRED) ---
    parser_name = "Parser Template"
    parser_description = "A new file parser."
    supported_extensions = []

    def can_parse(self, filepath, file_content_sample):
        \"\"\"
        (REQUIRED)
        Returns a confidence score (0-100) of how likely this
        parser is to handle the given file.
        \"\"\"
        return 0

    def parse(self, filepath, is_batch=False):
        \"\"\"
        (REQUIRED)
        Parses the file and returns a list of dictionaries.
        
        Args:
            filepath (Path): The Path object to the file.
            is_batch (bool): True if running in non-interactive batch mode.
        \"\"\"
        parsed_data = []

        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue 

                    # --- "Base Record + Enrich" Pattern ---
                    
                    # 1. Create a "base" record for EVERY line
                    record = {
                        'Timestamp_UTC': None,
                        'parse_status': 'UNPARSED',
                        'raw_log': line
                    }

                    # 2. Try to parse and "enrich" the record
                    # match = EXAMPLE_REGEX.match(line)
                    # if match:
                    #     parsed_fields = dict(zip(EXAMPLE_HEADERS, match.groups()))
                    #     record.update(parsed_fields) 
                    #     record['parse_status'] = 'SUCCESS'
                    #     record['Timestamp_UTC'] = self._normalize_time(
                    #         record.get('original_timestamp')
                    #     )
                    
                    parsed_data.append(record)
                    
        except Exception as e:
            logger.error(f"Error parsing file {filepath.name}: {e}", exc_info=True)
            
        return parsed_data

    # --- HELPER METHODS ---
    # def _normalize_time(self, timestamp_str):
    #     \"\"\"
    #     Converts a custom timestamp string to a standardized 
    #     UTC ISO-8601 string (YYYY-MM-DDTHH:MM:SSZ).
    #     \"\"\"
    #     if not timestamp_str:
    #         return None
    #         
    #     dt = None
    #     try:
    #         # ... (Try parsing logic) ...
    #         # dt = datetime.strptime(timestamp_str, '...')
    #         pass
    #     except (ValueError, TypeError):
    #         logger.warning(f"Could not parse timestamp: {timestamp_str}")
    #         return str(timestamp_str) # Return original on failure
    # 
    #     # --- Standardize the output ---
    #     if dt:
    #         try:
    #             if dt.tzinfo is None:
    #                 dt = dt.replace(tzinfo=timezone.utc)
    #             dt_utc = dt.astimezone(timezone.utc)
    #             dt_no_micros = dt_utc.replace(microsecond=0)
    #             return dt_no_micros.isoformat().replace('+00:00', 'Z')
    #         except Exception as e:
    #             logger.warning(f"Error standardizing timestamp for '{timestamp_str}': {e}")
    #
    #     return str(timestamp_str)
"""

# --- V2: STRING PARSER TEMPLATE ---

STRING_PARSER_TEMPLATE_STRING = """
# This file was auto-generated by Parser Tongue.

import logging
import re
import base64
from datetime import datetime, timezone

# Get a logger instance
logger = logging.getLogger(__name__)

class StringParserTemplate:
    \"\"\"
    This is the template class for a Parser Tongue string parser.
    \"\"\"

    # --- PARSER METADATA (REQUIRED) ---
    parser_name = "String Parser Template"
    parser_description = "A new string parser."

    def can_parse_string(self, input_string):
        \"\"\"
        (REQUIRED)
        Returns a confidence score (0-100) of how likely this
        parser is to handle the given string.
        \"\"\"
        # Example: Check for 'powershell -enc'
        # if 'powershell' in input_string.lower() and ' -enc' in input_string.lower():
        #     return 90
        return 0

    def parse_string(self, input_string):
        \"\"\"
        (REQUIRED)
        Parses the string and returns a SINGLE dictionary of key-value pairs.
        
        Args:
            input_string (str): The raw string from the CLI.
            
        Returns:
            dict: A dictionary of parsed values.
        \"\"\"
        
        parsed_data = {
            'original_string': input_string
        }
        
        try:
            # --- TODO: Add parsing logic ---
            # Example: Base64 decoding
            # if re.match(r'^[A-Za-z0-9+/=]+$', input_string):
            #     try:
            #         # Add padding if needed
            #         missing_padding = len(input_string) % 4
            #         if missing_padding:
            #             input_string += '=' * (4 - missing_padding)
            #         decoded_bytes = base64.b64decode(input_string)
            #         decoded_string = decoded_bytes.decode('utf-8', 'ignore')
            #         parsed_data['decoded_string'] = decoded_string
            #         parsed_data['parse_status'] = 'SUCCESS'
            #     except Exception as e:
            #         parsed_data['error'] = str(e)
            #         parsed_data['parse_status'] = 'FAILED'
            
            pass
            
        except Exception as e:
            logger.error(f"Error parsing string: {e}", exc_info=True)
            parsed_data['error'] = str(e)
            parsed_data['parse_status'] = 'FAILED'
            
        return parsed_data
"""

